texas_death_row/config/routes.rb
TexasDeathRow::Application.routes.draw do
  resources :executions

  root 'executions#index'

  

end

texas_death_row/app/models/execution.rb
class Execution < ActiveRecord::Base
	def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end
end

texas_death_row/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

texas_death_row/app/controllers/executions_controller.rb
class ExecutionsController < ApplicationController
  before_action :set_execution, only: [:show, :edit, :update, :destroy]

  # GET /executions
  # GET /executions.json
  def index
    @executions = Execution.all
		respond_to do |format|
			format.html
			format.csv { send_data @executions.to_csv }
			format.xls
			format.json { render json: @executions.to_json }
		end
  end

  # GET /executions/1
  # GET /executions/1.json
  def show
  end

  # GET /executions/new
  def new
    @execution = Execution.new
  end

  # GET /executions/1/edit
  def edit
  end

  # POST /executions
  # POST /executions.json
  def create
    @execution = Execution.new(execution_params)

    respond_to do |format|
      if @execution.save
        format.html { redirect_to @execution, notice: 'Execution was successfully created.' }
        format.json { render action: 'show', status: :created, location: @execution }
      else
        format.html { render action: 'new' }
        format.json { render json: @execution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /executions/1
  # PATCH/PUT /executions/1.json
  def update
    respond_to do |format|
      if @execution.update(execution_params)
        format.html { redirect_to @execution, notice: 'Execution was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @execution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /executions/1
  # DELETE /executions/1.json
  def destroy
    @execution.destroy
    respond_to do |format|
      format.html { redirect_to executions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_execution
      @execution = Execution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def execution_params
      params.require(:execution).permit(:age, :age_at_offense, :age_when_received, :codefendants, :computed_age_at_offense, :computed_age_executed, :computed_age_recieved, :computed_days_before_received_after_offense, :computed_days_between_received_and_executed, :county, :date_executed, :date_received, :dob, :edu_level, :eyes, :first_name, :gender, :height, :info_sheet, :last_name, :last_statement, :number, :offense_date, :prior_occupation, :prior_record, :race, :summary, :tdcj, :victim_info, :weight)
    end
end

texas_death_row/app/helpers/application_helper.rb
module ApplicationHelper
end

texas_death_row/app/helpers/executions_helper.rb
module ExecutionsHelper
end

texas_death_row/app/views/executions/_form.html.erb
<%= form_for(@execution) do |f| %>
  <% if @execution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@execution.errors.count, "error") %> prohibited this execution from being saved:</h2>

      <ul>
      <% @execution.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age, :id => "age_field" %>
  </div>
  <div class="field">
    <%= f.label :age_at_offense %><br>
    <%= f.text_field :age_at_offense, :id => "age_at_offense_field" %>
  </div>
  <div class="field">
    <%= f.label :age_when_received %><br>
    <%= f.text_field :age_when_received, :id => "age_when_received_field" %>
  </div>
  <div class="field">
    <%= f.label :codefendants %><br>
    <%= f.text_field :codefendants, :id => "codefendants_field" %>
  </div>
  <div class="field">
    <%= f.label :computed_age_at_offense %><br>
    <%= f.text_field :computed_age_at_offense, :id => "computed_age_at_offense_field" %>
  </div>
  <div class="field">
    <%= f.label :computed_age_executed %><br>
    <%= f.text_field :computed_age_executed, :id => "computed_age_executed_field" %>
  </div>
  <div class="field">
    <%= f.label :computed_age_recieved %><br>
    <%= f.text_field :computed_age_recieved, :id => "computed_age_recieved_field" %>
  </div>
  <div class="field">
    <%= f.label :computed_days_before_received_after_offense %><br>
    <%= f.text_field :computed_days_before_received_after_offense, :id => "computed_days_before_received_after_offense_field" %>
  </div>
  <div class="field">
    <%= f.label :computed_days_between_received_and_executed %><br>
    <%= f.text_field :computed_days_between_received_and_executed, :id => "computed_days_between_received_and_executed_field" %>
  </div>
  <div class="field">
    <%= f.label :county %><br>
    <%= f.text_field :county, :id => "county_field" %>
  </div>
  <div class="field">
    <%= f.label :date_executed %><br>
    <%= f.text_field :date_executed, :id => "date_executed_field" %>
  </div>
  <div class="field">
    <%= f.label :date_received %><br>
    <%= f.text_field :date_received, :id => "date_received_field" %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.text_field :dob, :id => "dob_field" %>
  </div>
  <div class="field">
    <%= f.label :edu_level %><br>
    <%= f.text_field :edu_level, :id => "edu_level_field" %>
  </div>
  <div class="field">
    <%= f.label :eyes %><br>
    <%= f.text_field :eyes, :id => "eyes_field" %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, :id => "first_name_field" %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.select :gender, [['Male'],['Female']], :id => "gender_field" %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height, :id => "height_field" %>
  </div>
  <div class="field">
    <%= f.label :info_sheet %><br>
    <%= f.text_field :info_sheet, :id => "info_sheet_field" %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, :id => "last_name_field" %>
  </div>
  <div class="field">
    <%= f.label :last_statement %><br>
    <%= f.text_field :last_statement, :id => "last_statement_field" %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number, :id => "number_field" %>
  </div>
  <div class="field">
    <%= f.label :offense_date %><br>
    <%= f.text_field :offense_date, :id => "offense_date_field" %>
  </div>
  <div class="field">
    <%= f.label :prior_occupation %><br>
    <%= f.text_field :prior_occupation, :id => "prior_occupation_field" %>
  </div>
  <div class="field">
    <%= f.label :prior_record %><br>
    <%= f.text_field :prior_record, :id => "prior_record_field" %>
  </div>
  <div class="field">
    <%= f.label :race %><br>
    <%= f.text_field :race, :id => "race_field" %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_field :summary, :id => "summary_field" %>
  </div>
  <div class="field">
    <%= f.label :tdcj %><br>
    <%= f.text_field :tdcj, :id => "tdcj_field" %>
  </div>
  <div class="field">
    <%= f.label :victim_info %><br>
    <%= f.text_field :victim_info, :id => "victim_info_field" %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight, :id => "weight_field" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

texas_death_row/app/views/executions/edit.html.erb
<h1>Editing execution <%= @execution.id %></h1>

<% if @execution.info_sheet.include? "jpg" %>
<img src="<%= @execution.info_sheet %>" style="float:right;">
<% end %>
<div id="form_container">
  <%= render 'form' %>
  <button id="do_the_math" class="btn btn-primary">Do The Math!</button>
  <%= link_to 'Show', @execution %> |
  <%= link_to 'Back', executions_path %>
</div>

texas_death_row/app/views/executions/index.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <h1 class="heading">The Texas 500</h1>
    </div>
  </div>
  <div class="row">
    <div class="span12" id="table_contain">
      <table id="executions_index_table" class="table table-condensed responsive">
      <thead>
        <tr>
          <th></th>
          <th></th>
          <th></th>
          <th>Number</th>
          <th>First name</th>
          <th>Last name</th>
          <th>Age</th>
          <th>Age at offense</th>
          <th>Age when received</th>
          <th>Codefendants</th>
          <th>Computed age at offense</th>
          <th>Computed age executed</th>
          <th>Computed age received</th>
          <th>Computed days before received after offense</th>
          <th>Computed days between received and executed</th>
          <th>County</th>
          <th>Date executed</th>
          <th>Date received</th>
          <th>Dob</th>
          <th>Edu level</th>
          <th>Eyes</th>
          <th>Gender</th>
          <th>Height</th>
          <!-- <th>Info sheet</th> -->
          <!-- <th>Last statement</th> -->
          <th>Offense date</th>
          <th>Prior occupation</th>
          <!-- <th>Prior record</th> -->
          <th>Race</th>
          <!-- <th>Summary</th> -->
          <th>Tdcj</th>
          <th>Victim info</th>
          <th>Weight</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @executions.each do |execution| %>
          <tr>
            <td><%= link_to 'Show', execution %></td>
            <td><%= link_to 'Edit', edit_execution_path(execution) %></td>
            <td><%= link_to 'Destroy', execution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <td><strong><%= "%03d" % execution.number %></strong></td>
            <td><%= execution.first_name %></td>
            <td><%= execution.last_name %></td>
            <td><%= execution.age %></td>
            <td><%= execution.age_at_offense %></td>
            <td><%= execution.age_when_received %></td>
            <td><%= execution.codefendants %></td>
            <td><%= execution.computed_age_at_offense %></td>
            <td><%= execution.computed_age_executed %></td>
            <td><%= execution.computed_age_recieved %></td>
            <td><%= execution.computed_days_before_received_after_offense %></td>
            <td><%= execution.computed_days_between_received_and_executed %></td>
            <td><%= execution.county %></td>
            <td><%= execution.date_executed %></td>
            <td><%= execution.date_received %></td>
            <td><%= execution.dob %></td>
            <td><%= execution.edu_level %></td>
            <td><%= execution.eyes %></td>
            <td><%= execution.gender %></td>
            <td><%= execution.height %></td>
            <!-- <td><%= execution.info_sheet %></td> -->
            <!-- <td><%= execution.last_statement %></td> -->
            <td><%= execution.offense_date %></td>
            <td><%= execution.prior_occupation %></td>
            <!-- <td><%= execution.prior_record %></td> -->
            <td><%= execution.race %></td>
            <!-- <td><%= execution.summary %></td> -->
            <td><%= execution.tdcj %></td>
            <td><%= execution.victim_info %></td>
            <td><%= execution.weight %></td>
            <td><%= link_to 'Show', execution %></td>
            <td><%= link_to 'Edit', edit_execution_path(execution) %></td>
            <td><%= link_to 'Destroy', execution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
      </table>
    </div>
  </div> 
</div>

texas_death_row/app/views/executions/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="AdTypes">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Age</Data></Cell>
        <Cell><Data ss:Type="String">Age at offense</Data></Cell>
        <Cell><Data ss:Type="String">Age when received</Data></Cell>
        <Cell><Data ss:Type="String">Codefendants</Data></Cell>
        <Cell><Data ss:Type="String">Computed age at offense</Data></Cell>
        <Cell><Data ss:Type="String">Computed age executed</Data></Cell>
        <Cell><Data ss:Type="String">Computed age recieved</Data></Cell>
        <Cell><Data ss:Type="String">Computed days before received after offense</Data></Cell>
        <Cell><Data ss:Type="String">Computed days between received and executed</Data></Cell>
        <Cell><Data ss:Type="String">County</Data></Cell>
        <Cell><Data ss:Type="String">Date executed</Data></Cell>
        <Cell><Data ss:Type="String">Date received</Data></Cell>
        <Cell><Data ss:Type="String">Dob</Data></Cell>
        <Cell><Data ss:Type="String">Edu level</Data></Cell>
        <Cell><Data ss:Type="String">Eyes</Data></Cell>
        <Cell><Data ss:Type="String">First name</Data></Cell>
        <Cell><Data ss:Type="String">Gender</Data></Cell>
        <Cell><Data ss:Type="String">Height</Data></Cell>
        <Cell><Data ss:Type="String">Info sheet</Data></Cell>
        <Cell><Data ss:Type="String">Last name</Data></Cell>
        <Cell><Data ss:Type="String">Last statement</Data></Cell>
        <Cell><Data ss:Type="String">Number</Data></Cell>
        <Cell><Data ss:Type="String">Offense date</Data></Cell>
        <Cell><Data ss:Type="String">Prior occupation</Data></Cell>
        <Cell><Data ss:Type="String">Prior record</Data></Cell>
        <Cell><Data ss:Type="String">Race</Data></Cell>
        <Cell><Data ss:Type="String">Summary</Data></Cell>
        <Cell><Data ss:Type="String">Tdcj</Data></Cell>
        <Cell><Data ss:Type="String">Victim info</Data></Cell>
        <Cell><Data ss:Type="String">Weight</Data></Cell>
      </Row>
    <% @executions.each do |execution| %>
      <Row>
        <Cell><Data ss:Type="String"><%= execution.age %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.age_at_offense %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.age_when_received %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.codefendants %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.computed_age_at_offense %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.computed_age_executed %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.computed_age_recieved %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.computed_days_before_received_after_offense %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.computed_days_between_received_and_executed %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.county %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.date_executed %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.date_received %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.dob %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.edu_level %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.eyes %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.first_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.gender %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.height %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.info_sheet %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.last_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.last_statement %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.number %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.offense_date %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.prior_occupation %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.prior_record %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.race %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.summary %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.tdcj %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.victim_info %></Data></Cell>
        <Cell><Data ss:Type="String"><%= execution.weight %>  </Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

texas_death_row/app/views/executions/new.html.erb
<h1>New execution</h1>

<%= render 'form' %>

<%= link_to 'Back', executions_path %>

texas_death_row/app/views/executions/show.html.erb
<% if @execution.info_sheet.include? "jpg" %>
<img src="<%= @execution.info_sheet %>" style="float:right;">
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Age:</strong>
  <%= @execution.age %>
</p>

<p>
  <strong>Age at offense:</strong>
  <%= @execution.age_at_offense %>
</p>

<p>
  <strong>Age when received:</strong>
  <%= @execution.age_when_received %>
</p>

<p>
  <strong>Codefendants:</strong>
  <%= @execution.codefendants %>
</p>

<p>
  <strong>Computed age at offense:</strong>
  <%= @execution.computed_age_at_offense %>
</p>

<p>
  <strong>Computed age executed:</strong>
  <%= @execution.computed_age_executed %>
</p>

<p>
  <strong>Computed age recieved:</strong>
  <%= @execution.computed_age_recieved %>
</p>

<p>
  <strong>Computed days before received after offense:</strong>
  <%= @execution.computed_days_before_received_after_offense %>
</p>

<p>
  <strong>Computed days between received and executed:</strong>
  <%= @execution.computed_days_between_received_and_executed %>
</p>

<p>
  <strong>County:</strong>
  <%= @execution.county %>
</p>

<p>
  <strong>Date executed:</strong>
  <%= @execution.date_executed %>
</p>

<p>
  <strong>Date received:</strong>
  <%= @execution.date_received %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @execution.dob %>
</p>

<p>
  <strong>Edu level:</strong>
  <%= @execution.edu_level %>
</p>

<p>
  <strong>Eyes:</strong>
  <%= @execution.eyes %>
</p>

<p>
  <strong>First name:</strong>
  <%= @execution.first_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @execution.gender %>
</p>

<p>
  <strong>Height:</strong>
  <%= @execution.height %>
</p>

<p>
  <strong>Info sheet:</strong>
  <%= @execution.info_sheet %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @execution.last_name %>
</p>

<p>
  <strong>Last statement:</strong>
  <%= @execution.last_statement %>
</p>

<p>
  <strong>Number:</strong>
  <%= @execution.number %>
</p>

<p>
  <strong>Offense date:</strong>
  <%= @execution.offense_date %>
</p>

<p>
  <strong>Prior occupation:</strong>
  <%= @execution.prior_occupation %>
</p>

<p>
  <strong>Prior record:</strong>
  <%= @execution.prior_record %>
</p>

<p>
  <strong>Race:</strong>
  <%= @execution.race %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @execution.summary %>
</p>

<p>
  <strong>Tdcj:</strong>
  <%= @execution.tdcj %>
</p>

<p>
  <strong>Victim info:</strong>
  <%= @execution.victim_info %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @execution.weight %>
</p>

<%= link_to 'Edit', edit_execution_path(@execution) %> |
<%= link_to 'Back', root_path %>

texas_death_row/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TexasDeathRow</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>